services:
  app:
    build:
      context: .
      # args:
      #   APT_PROXY: http://192.168.0.4:3142
      #   PYPI_PROXY: http://192.168.0.4:3141/root/pypi/+simple/
    container_name: ocr-pdf-web-app
    init: true
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
    ports:
      - "8502:8502"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 60s
      timeout: 10s
      start_period: 30s
